name: 'poc-php'
'on':
    push:
        branches:
            - master
            - develop
    pull_request: 
        branches:
            - main
            - develop
jobs:
    lint:
        strategy:
            fail-fast: false
            matrix:
                operating-system:
                    - ubuntu-latest
                php-versions:
                    - '7.3'
        runs-on: '${{ matrix.operating-system }}'
        name: 'Lint / PHP ${{ matrix.php-versions }} @ ${{ matrix.operating-system }}'
        steps:
          - name: 'Install dependencies with Composer'
            run: 'composer install --prefer-dist '

          - name: 'Linter tests files'
            run: 'php -l tests'

          - name: Run linters
            uses: wearerequired/lint-action@v2
            with:
              php_codesniffer: true