name: 'poc-php'

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
        php-versions:
          - '7.3'

    runs-on: '${{ matrix.operating-system }}'

    name: 'Lint and Test / PHP ${{ matrix.php-versions }} @ ${{ matrix.operating-system }}'

    steps:
      - name: 'Install dependencies with Composer'
        run: 'composer install --prefer-dist'

      - name: 'Run Tests'
        run: 'composer test tests'

      - name: 'Run linters'
        run: composer lint srs
